# Generated by Django 3.0.3 on 2020-03-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='name',
            new_name='client_name',
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='testimonials/', verbose_name='Profile Picture'),
        ),
    ]
