QUESTION_STATUS_PUBLISHED_TEXT = 'Published'
QUESTION_STATUS_DRAFT_TEXT = 'Draft'
QUESTION_STATUS_REJECTED_TEXT = 'Rejected'

QUESTION_STATUS_PUBLISHED = '1'
QUESTION_STATUS_DRAFT = '2'
QUESTION_STATUS_REJECTED = '3'


MINIMUM_ANSWER_VALIDATION = 'You Have To Add Atleast Two Answer'
MINIMUM_CORRECT_ANSWER_VALIDATION = 'You Have To Add Atleast One Correct Answer'
QUESTION_IMPORT_INVALID_COLUMN_ERROR_MSG = "Invalid Excel Format. Please download the template and don't modify the header"
EMPTY_EXCEL_FILE_FORMAT_MSG = 'Empty Excel File'
EXCEL_COLUMN_QUESTION = 'Question'
EXCEL_COLUMN_SUBJECT = 'Subject'
EXCEL_COLUMN_TOPIC = 'Topic'
EXCEL_COLUMN_SUBTOPIC = 'Subtopic'
EXCEL_COLUMN_DIFFICULTIES = 'Difficulties'
EXCEL_COLUMN_QTYPE = 'Type'
EXCEL_COLUMN_OPTION_ONE = 'Option One'
EXCEL_COLUMN_OPTION_ONE_CORRECT = 'Option One Correct'
EXCEL_COLUMN_OPTION_TWO = 'Option Two'
EXCEL_COLUMN_OPTION_TWO_CORRECT = 'Option Two Correct'
EXCEL_COLUMN_OPTION_THREE = 'Option Three'
EXCEL_COLUMN_OPTION_THREE_CORRECT = 'Option Three Correct'
EXCEL_COLUMN_OPTION_FOUR = 'Option Four'
EXCEL_COLUMN_OPTION_FOUR_CORRECT = 'Option Four Correct'
EXCEL_COLUMN_OPTION_FIVE = 'Option Five'
EXCEL_COLUMN_OPTION_FIVE_CORRECT = 'Option Five Correct'
INVALID_EXCEL_FILE_FORMAT_MSG = 'Invalid Excel File'
EXCEL_CONTENT_TYPE_XLSX = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
EXCEL_CONTENT_TYPE_XLX = "application/vnd.ms-excel"
