NOTIFICATION_VERBOSE_NAME = 'Notification'
NOTIFICATION_VERBOSE_NAME_PLURAL = 'Notifications'
EMPLOYER_MESSAGE_VERBOSE_NAME = 'Employer Message'
EMPLOYER_MESSAGE_VERBOSE_NAME_PLURAL = 'Employer Messages'