# Generated by Django 3.0.3 on 2020-04-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_advice', '0002_auto_20200324_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='careeradvice',
            name='short_description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
