# Generated by Django 3.0.3 on 2020-04-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_advice', '0003_careeradvice_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careeradvice',
            name='author',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='careeradvice',
            name='short_description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='careeradvice',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
