# Generated by Django 3.0.3 on 2020-04-12 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career_advice', '0004_auto_20200406_0429'),
        ('career_advice', '0004_auto_20200408_0830'),
    ]

    operations = [
    ]
