# Generated by Django 3.0.3 on 2020-04-14 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career_advice', '0005_merge_20200412_1030'),
        ('career_advice', '0005_merge_20200412_0918'),
    ]

    operations = [
    ]
