# Generated by Django 3.0.3 on 2020-06-14 11:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_advice', '0007_auto_20200418_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careeradvice',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='careeradvice',
            name='short_description',
            field=models.CharField(max_length=600),
        ),
    ]
