# Generated by Django 3.0.3 on 2020-06-15 08:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_advice', '0008_auto_20200614_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careeradvice',
            name='created_date',
        ),
        migrations.AddField(
            model_name='careeradvice',
            name='archived_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='careeradvice',
            name='archived_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='careeradvice',
            name='archived_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='careeradvice',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='careeradvice',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='careeradvice',
            name='created_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='careeradvice',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='careeradvice',
            name='modified_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='careeradvice',
            name='modified_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='careeradvice',
            name='modified_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='careeradvice',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='careeradvice',
            name='short_description',
            field=models.TextField(),
        ),
    ]
