# Generated by Django 3.0.3 on 2020-07-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_advice', '0009_auto_20200615_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='careeradvice',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='careeradvice',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
