# Generated by Django 3.0.3 on 2020-07-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_advice', '0010_auto_20200701_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careeradvice',
            name='thumbnail_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
