# Generated by Django 3.0.3 on 2020-08-19 11:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('career_advice', '0011_auto_20200725_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='careeradvice',
            name='posted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
