# Generated by Django 3.0.3 on 2020-03-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='logo_url',
            field=models.ImageField(blank=True, upload_to='logo/'),
        ),
    ]
