# Generated by Django 3.0.3 on 2020-04-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20200401_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='appstore_url',
            field=models.URLField(blank=True, null=True, verbose_name='App Store URL'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='playstore_url',
            field=models.URLField(blank=True, null=True, verbose_name='Play Store URL'),
        ),
    ]
