# Generated by Django 3.0.3 on 2020-04-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_auto_20200409_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='appstore_url',
            field=models.URLField(verbose_name='App Store URL'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='playstore_url',
            field=models.URLField(verbose_name='Play Store URL'),
        ),
    ]
