# Generated by Django 3.0.3 on 2020-05-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_auto_20200520_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='zoom',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
    ]
