# Generated by Django 3.0.3 on 2020-05-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_settings_zoom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='zoom',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
    ]
