# Generated by Django 3.0.3 on 2020-06-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_auto_20200615_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
