# Generated by Django 3.0.3 on 2020-09-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_auto_20200823_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='minimum_profile_completeness',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
