# Generated by Django 3.0.3 on 2020-09-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0015_settings_minimum_profile_completeness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='minimum_profile_completeness',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
