# Generated by Django 3.0.3 on 2020-09-13 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0018_auto_20200913_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='no_replay_sender_host_password',
            new_name='no_reply_sender_host_password',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='no_replay_sender_host_user',
            new_name='no_reply_sender_host_user',
        ),
    ]
