# Generated by Django 3.0.3 on 2020-07-11 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0090_auto_20200628_2031'),
        ('pro', '0047_auto_20200704_1142'),
        ('messaging', '0002_auto_20200615_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employermessage',
            name='recipient',
        ),
        migrations.AddField(
            model_name='employermessage',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_msgs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employermessage',
            name='receiver_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='com_received_msgs', to='job.Company'),
        ),
        migrations.AddField(
            model_name='employermessage',
            name='receiver_pro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pro_received_msgs', to='pro.Professional'),
        ),
        migrations.AddField(
            model_name='employermessage',
            name='receiver_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employermessage',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_msgs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employermessage',
            name='sender_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='com_sent_msgs', to='job.Company'),
        ),
        migrations.AddField(
            model_name='employermessage',
            name='sender_pro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pro_sent_msgs', to='pro.Professional'),
        ),
        migrations.AddField(
            model_name='employermessage',
            name='sender_type',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
