# Generated by Django 3.0.3 on 2020-09-14 14:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0004_fcmcloudmessaging'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fcmcloudmessaging',
            unique_together={('user', 'fcm_token', 'device_id')},
        ),
    ]
