# Generated by Django 3.0.3 on 2020-02-12 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20200212_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
