# Generated by Django 3.0.3 on 2020-02-15 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20200215_0633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='addres',
            new_name='address',
        ),
    ]
