# Generated by Django 3.0.3 on 2020-02-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20200217_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='contact_no',
        ),
        migrations.AddField(
            model_name='company',
            name='company_contact_no_one',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_contact_no_three',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_contact_no_two',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_name_bdjobs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_name_facebook',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_name_google',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
