# Generated by Django 3.0.3 on 2020-02-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_auto_20200217_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_profile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
