# Generated by Django 3.0.3 on 2020-02-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_company_company_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact_person_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
