# Generated by Django 3.0.3 on 2020-03-23 07:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_job_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career_Advice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Career advice',
                'verbose_name_plural': 'Career advices',
                'db_table': 'career advices',
            },
        ),
    ]
