# Generated by Django 3.0.3 on 2020-03-22 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingKeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('count', models.PositiveIntegerField(default=1)),
                ('created_date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'verbose_name': 'TrendingKeyword',
                'verbose_name_plural': 'TrendingKeywords',
                'db_table': 'trending_keywords',
            },
        ),
    ]
