# Generated by Django 3.0.3 on 2020-03-22 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_skill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
    ]
