# Generated by Django 3.0.3 on 2020-03-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='raw_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
