# Generated by Django 3.0.3 on 2020-03-23 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_career_advice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Career_Advice',
        ),
    ]
