# Generated by Django 3.0.3 on 2020-03-23 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_job_raw_content'),
        ('job', '0015_trendingkeywords'),
    ]

    operations = [
    ]
