# Generated by Django 3.0.3 on 2020-03-23 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_skill_job'),
        ('job', '0015_auto_20200322_0625'),
    ]

    operations = [
    ]
