# Generated by Django 3.0.3 on 2020-03-23 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_merge_20200323_1126'),
        ('job', '0016_merge_20200323_0955'),
    ]

    operations = [
    ]
