# Generated by Django 3.0.3 on 2020-03-24 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_merge_20200323_0837'),
        ('job', '0016_merge_20200323_1126'),
        ('job', '0015_delete_career_advice'),
        ('job', '0018_job_terms_and_condition'),
    ]

    operations = [
    ]
