# Generated by Django 3.0.3 on 2020-03-25 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0019_merge_20200324_0617'),
        ('job', '0019_merge_20200324_0643'),
    ]

    operations = [
    ]
