# Generated by Django 3.0.3 on 2020-03-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0019_merge_20200324_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_skills',
            field=models.ManyToManyField(blank=True, to='job.Skill'),
        ),
    ]
