# Generated by Django 3.0.3 on 2020-03-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0021_remove_trendingkeywords_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
