# Generated by Django 3.0.3 on 2020-03-25 12:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0022_company_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=datetime.date.today)),
                ('job', models.ForeignKey(db_column='job', on_delete=django.db.models.deletion.PROTECT, to='job.Job')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bookmark Job',
                'verbose_name_plural': 'Bookmark Jobs',
                'db_table': 'bookmark_jobs',
            },
        ),
    ]
