# Generated by Django 3.0.3 on 2020-03-28 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0023_merge_20200328_0453'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job_skill_detail',
        ),
    ]
