# Generated by Django 3.0.3 on 2020-03-29 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0023_bookmarkjob'),
        ('job', '0024_delete_job_skill_detail'),
    ]

    operations = [
    ]
