# Generated by Django 3.0.3 on 2020-03-29 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0025_merge_20200329_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='industry',
            field=models.ForeignKey(blank=True, db_column='industry', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='industries', to='job.Industry'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_skills',
            field=models.ManyToManyField(blank=True, related_name='skill_set', to='job.Skill'),
        ),
    ]
