# Generated by Django 3.0.3 on 2020-03-30 10:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0026_auto_20200329_0654'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookmarkJob',
            new_name='FavouriteJob',
        ),
    ]
