# Generated by Django 3.0.3 on 2020-03-30 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0026_auto_20200329_0654'),
        ('job', '0019_merge_20200328_0647'),
    ]

    operations = [
    ]
