# Generated by Django 3.0.3 on 2020-04-01 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_merge_20200323_1128'),
        ('job', '0027_merge_20200330_0338'),
    ]

    operations = [
    ]
