# Generated by Django 3.0.3 on 2020-04-05 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0027_auto_20200330_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritejob',
            name='job',
            field=models.ForeignKey(db_column='job', on_delete=django.db.models.deletion.PROTECT, related_name='fav_jobs', to='job.Job'),
        ),
        migrations.AlterModelTable(
            name='favouritejob',
            table='favourite_jobs',
        ),
    ]
