# Generated by Django 3.0.3 on 2020-04-05 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0028_merge_20200401_0840'),
        ('job', '0028_auto_20200405_0426'),
    ]

    operations = [
    ]
