# Generated by Django 3.0.3 on 2020-04-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0029_merge_20200405_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
