# Generated by Django 3.0.3 on 2020-04-15 05:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0029_merge_20200405_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 15, 5, 0, 15, 310592, tzinfo=utc)),
        ),
    ]
