# Generated by Django 3.0.3 on 2020-04-09 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0029_merge_20200405_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company_name',
        ),
    ]
