# Generated by Django 3.0.3 on 2020-04-09 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0030_remove_job_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_name',
            field=models.ForeignKey(blank=True, db_column='company', null=True, on_delete=django.db.models.deletion.PROTECT, to='job.Company'),
        ),
    ]
