# Generated by Django 3.0.3 on 2020-04-15 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0031_auto_20200415_1109'),
        ('job', '0031_auto_20200415_1125'),
    ]

    operations = [
    ]
