# Generated by Django 3.0.3 on 2020-04-15 05:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0033_auto_20200415_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 5, 53, 11, 806226, tzinfo=utc)),
        ),
    ]
