# Generated by Django 3.0.3 on 2020-04-10 05:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0033_auto_20200409_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.ForeignKey(blank=True, db_column='company', null=True, on_delete=django.db.models.deletion.PROTECT, to='job.Company'),
        ),
        migrations.AlterField(
            model_name='trendingkeywords',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
