# Generated by Django 3.0.3 on 2020-04-10 05:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0034_auto_20200410_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trendingkeywords',
            name='created_date',
        ),
        migrations.AddField(
            model_name='trendingkeywords',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
