# Generated by Django 3.0.3 on 2020-04-10 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0035_auto_20200410_0553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trendingkeywords',
            name='date',
        ),
        migrations.AddField(
            model_name='trendingkeywords',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
