# Generated by Django 3.0.3 on 2020-04-10 06:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0036_auto_20200410_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendingkeywords',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
