# Generated by Django 3.0.3 on 2020-04-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0037_auto_20200410_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendingkeywords',
            name='browser_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='trendingkeywords',
            name='ip_address',
            field=models.CharField(default='0.0.0.0', max_length=255),
        ),
        migrations.AddField(
            model_name='trendingkeywords',
            name='operating_system',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
