# Generated by Django 3.0.3 on 2020-04-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0038_auto_20200410_0623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trendingkeywords',
            old_name='browser_name',
            new_name='browser',
        ),
        migrations.RemoveField(
            model_name='trendingkeywords',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='trendingkeywords',
            name='device',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
