# Generated by Django 3.0.3 on 2020-04-12 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0031_auto_20200412_0516'),
        ('job', '0039_auto_20200411_0409'),
    ]

    operations = [
    ]
