# Generated by Django 3.0.3 on 2020-04-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0040_merge_20200412_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
