# Generated by Django 3.0.3 on 2020-04-13 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0041_job_entry_date'),
        ('job', '0041_job_slug'),
    ]

    operations = [
    ]
