# Generated by Django 3.0.3 on 2020-04-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0042_auto_20200414_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyonline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='applyonline',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
