# Generated by Django 3.0.3 on 2020-04-15 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0042_merge_20200414_0653'),
        ('job', '0042_merge_20200413_1421'),
    ]

    operations = [
    ]
