# Generated by Django 3.0.3 on 2020-04-15 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0043_merge_20200415_0418'),
        ('job', '0034_auto_20200415_1153'),
    ]

    operations = [
    ]
