# Generated by Django 3.0.3 on 2020-04-15 06:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0044_merge_20200415_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 6, 12, 45, 544055, tzinfo=utc)),
        ),
    ]
