# Generated by Django 3.0.3 on 2020-04-15 10:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0045_auto_20200415_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 10, 42, 37, 979396, tzinfo=utc)),
        ),
    ]
