# Generated by Django 3.0.3 on 2020-04-16 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0043_auto_20200415_0241'),
        ('job', '0045_auto_20200415_1212'),
    ]

    operations = [
    ]
