# Generated by Django 3.0.3 on 2020-04-15 11:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0046_auto_20200415_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 11, 25, 36, 624742, tzinfo=utc)),
        ),
    ]
