# Generated by Django 3.0.3 on 2020-04-15 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0047_auto_20200415_1725'),
        ('job', '0046_auto_20200415_1642'),
    ]

    operations = [
    ]
