# Generated by Django 3.0.3 on 2020-04-19 05:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0047_auto_20200418_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 5, 6, 26, 751617, tzinfo=utc)),
        ),
    ]
