# Generated by Django 3.0.3 on 2020-04-19 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0046_auto_20200418_1744'),
        ('job', '0047_auto_20200418_1743'),
        ('job', '0046_auto_20200418_1623'),
    ]

    operations = [
    ]
