# Generated by Django 3.0.3 on 2020-04-19 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0048_merge_20200415_2120'),
        ('job', '0048_merge_20200419_0916'),
        ('job', '0046_merge_20200416_1650'),
        ('job', '0048_auto_20200419_1106'),
    ]

    operations = [
    ]
