# Generated by Django 3.0.3 on 2020-04-19 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0046_auto_20200418_1623'),
        ('job', '0048_auto_20200419_1106'),
        ('job', '0048_merge_20200415_2120'),
        ('job', '0046_auto_20200418_1744'),
    ]

    operations = [
    ]
