# Generated by Django 3.0.3 on 2020-04-19 11:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0049_merge_20200419_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applied_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='favorite_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 11, 1, 32, 124950, tzinfo=utc)),
        ),
    ]
