# Generated by Django 3.0.3 on 2020-04-19 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0048_auto_20200419_1650'),
        ('job', '0046_merge_20200416_1650'),
        ('job', '0051_auto_20200419_1810'),
    ]

    operations = [
    ]
