# Generated by Django 3.0.3 on 2020-04-20 03:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0053_auto_20200419_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 3, 11, 56, 825043, tzinfo=utc)),
        ),
    ]
