# Generated by Django 3.0.3 on 2020-04-21 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0049_merge_20200419_1505'),
        ('job', '0054_auto_20200420_0911'),
    ]

    operations = [
    ]
