# Generated by Django 3.0.3 on 2020-04-21 05:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0056_auto_20200421_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 21, 5, 26, 52, 625630, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
