# Generated by Django 3.0.3 on 2020-04-22 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0050_auto_20200419_1701'),
        ('job', '0060_auto_20200421_1129'),
    ]

    operations = [
    ]
