# Generated by Django 3.0.3 on 2020-04-22 05:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0061_merge_20200422_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 22, 5, 11, 46, 420533, tzinfo=utc)),
        ),
    ]
