# Generated by Django 3.0.3 on 2020-04-22 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0061_merge_20200422_0957'),
        ('job', '0061_merge_20200422_1133'),
    ]

    operations = [
    ]
