# Generated by Django 3.0.3 on 2020-04-22 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0062_merge_20200422_1252'),
        ('job', '0062_auto_20200422_1111'),
    ]

    operations = [
    ]
