# Generated by Django 3.0.3 on 2020-04-29 04:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0064_auto_20200422_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='trendingkeywords',
            name='keyword',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='trendingkeywords',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
