# Generated by Django 3.0.3 on 2020-04-25 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0050_auto_20200419_1815'),
        ('job', '0064_auto_20200422_1305'),
    ]

    operations = [
    ]
