# Generated by Django 3.0.3 on 2020-04-26 05:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0065_merge_20200425_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 5, 39, 12, 264092, tzinfo=utc)),
        ),
    ]
