# Generated by Django 3.0.3 on 2020-04-26 06:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0066_auto_20200426_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 6, 28, 7, 957372, tzinfo=utc)),
        ),
    ]
