# Generated by Django 3.0.3 on 2020-05-01 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0068_auto_20200426_1252'),
        ('job', '0065_auto_20200429_1057'),
    ]

    operations = [
    ]
