# Generated by Django 3.0.3 on 2020-05-02 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0069_merge_20200501_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-entry_date'], 'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
    ]
