# Generated by Django 3.0.3 on 2020-05-03 11:27

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0070_auto_20200502_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_from', models.CharField(max_length=255, null=True)),
                ('modified_by', models.CharField(max_length=255, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_from', models.CharField(max_length=255, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_by', models.CharField(max_length=255, null=True)),
                ('archived_at', models.DateTimeField(null=True)),
                ('archived_from', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Job Category',
                'verbose_name_plural': 'Job Categories',
                'db_table': 'job_categories',
            },
        ),
        migrations.CreateModel(
            name='JobGender',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_from', models.CharField(max_length=255, null=True)),
                ('modified_by', models.CharField(max_length=255, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_from', models.CharField(max_length=255, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_by', models.CharField(max_length=255, null=True)),
                ('archived_at', models.DateTimeField(null=True)),
                ('archived_from', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Gender Preference(Job)',
                'verbose_name_plural': 'Gender Preferences(Job)',
                'db_table': 'job_genders',
            },
        ),
        migrations.CreateModel(
            name='JobSource',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_from', models.CharField(max_length=255, null=True)),
                ('modified_by', models.CharField(max_length=255, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_from', models.CharField(max_length=255, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_by', models.CharField(max_length=255, null=True)),
                ('archived_at', models.DateTimeField(null=True)),
                ('archived_from', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Job Source',
                'verbose_name_plural': 'Job Sources',
                'db_table': 'job_sources',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='additional_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='approve_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='archived_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='archived_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='archived_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='company_area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='company_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='company_country',
            field=django_countries.fields.CountryField(default='BD', max_length=2),
        ),
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='created_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='creator_type',
            field=models.CharField(choices=[('OPERATOR', 'Operator'), ('SYSTEM', 'System'), ('COMPANY', 'Company')], default='OPERATOR', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='job_area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_country',
            field=django_countries.fields.CountryField(default='BD', max_length=2),
        ),
        migrations.AddField(
            model_name='job',
            name='job_nature',
            field=models.CharField(choices=[('FULLTIME', 'Full-time'), ('PARTTIME', 'Part-time')], default='FULLTIME', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='job_site',
            field=models.CharField(choices=[('ONSITE', 'On-site'), ('REMOTE', 'Remote')], default='ONSITE', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('PERMANENT', 'Permanent'), ('CONTRACTUAL', 'Contractual')], default='PERMANENT', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='job_url_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_url_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_url_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='modified_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='modified_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='post_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='publish_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='review_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='job_category',
            field=models.ForeignKey(db_column='job_category', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='job.JobCategory'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_gender',
            field=models.ForeignKey(db_column='job_gender', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='job.JobGender'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_source_1',
            field=models.ForeignKey(blank=True, db_column='job_source_1', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs1', to='job.JobSource'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_source_2',
            field=models.ForeignKey(blank=True, db_column='job_source_2', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs2', to='job.JobSource'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_source_3',
            field=models.ForeignKey(blank=True, db_column='job_source_3', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs3', to='job.JobSource'),
        ),
    ]
