# Generated by Django 3.0.3 on 2020-05-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0072_auto_20200504_1025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-post_date'], 'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
        migrations.RenameField(
            model_name='job',
            old_name='job_location',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='company_location',
            new_name='company_address',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='descriptions',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='job',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='employment_status',
        ),
        migrations.RemoveField(
            model_name='job',
            name='entry_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='job',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='job',
            name='web_address',
        ),
        migrations.RemoveField(
            model_name='job',
            name='zipcode',
        ),
        migrations.AlterField(
            model_name='job',
            name='company_profile',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
