# Generated by Django 3.0.3 on 2020-05-18 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0074_auto_20200512_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.ForeignKey(db_column='company', on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='job.Company'),
        ),
    ]
