# Generated by Django 3.0.3 on 2020-05-21 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0075_auto_20200518_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyonline',
            name='job',
            field=models.ForeignKey(db_column='job', on_delete=django.db.models.deletion.PROTECT, related_name='applied_jobs', to='job.Job'),
        ),
    ]
