# Generated by Django 3.0.3 on 2020-06-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0079_auto_20200602_1754'),
    ]

    operations = [
            migrations.RunSQL("UPDATE jobs SET experience=1 WHERE experience='1 Year'"),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        )
    ]
