# Generated by Django 3.0.3 on 2020-06-08 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0080_auto_20200603_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_from', models.CharField(max_length=255, null=True)),
                ('modified_by', models.CharField(max_length=255, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_from', models.CharField(max_length=255, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_by', models.CharField(max_length=255, null=True)),
                ('archived_at', models.DateTimeField(null=True)),
                ('archived_from', models.CharField(max_length=255, null=True)),
                ('is_shortlisted', models.BooleanField(default=False)),
                ('job', models.ForeignKey(db_column='job', on_delete=django.db.models.deletion.PROTECT, related_name='applied_jobs', to='job.Job')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'db_table': 'job_applications',
            },
        ),
        migrations.AlterModelOptions(
            name='favouritejob',
            options={'verbose_name': 'Favorite Job', 'verbose_name_plural': 'Favorite Jobs'},
        ),
        migrations.DeleteModel(
            name='ApplyOnline',
        ),
    ]
