# Generated by Django 3.0.3 on 2020-06-08 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0041_auto_20200608_1527'),
        ('job', '0081_auto_20200608_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='pro',
            field=models.ForeignKey(db_column='pro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applied_pros', to='pro.Professional'),
        ),
    ]
