# Generated by Django 3.0.3 on 2020-06-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0085_auto_20200615_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
    ]
