# Generated by Django 3.0.3 on 2020-06-23 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0088_auto_20200623_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favouritejob',
            name='user',
        ),
    ]
