# Generated by Django 3.0.3 on 2020-06-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0089_remove_favouritejob_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, choices=[('Dhaka, Bangladesh', 'Dhaka, Bangladesh'), ('Chittagong, Bangladesh', 'Chittagong, Bangladesh'), ('Sylhet, Bangladesh', 'Sylhet, Bangladesh'), ('Gazipur, Bangladesh', 'Gazipur, Bangladesh'), ('Narayangang, Bangladesh', 'Narayangang, Bangladesh'), ('Khulna, Bangladesh', 'Khulna, Bangladesh'), ('London, United Kingdom', 'London, United Kingdom')], default='Dhaka, Bangladesh', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_city',
            field=models.CharField(blank=True, choices=[('Dhaka, Bangladesh', 'Dhaka, Bangladesh'), ('Chittagong, Bangladesh', 'Chittagong, Bangladesh'), ('Sylhet, Bangladesh', 'Sylhet, Bangladesh'), ('Gazipur, Bangladesh', 'Gazipur, Bangladesh'), ('Narayangang, Bangladesh', 'Narayangang, Bangladesh'), ('Khulna, Bangladesh', 'Khulna, Bangladesh'), ('London, United Kingdom', 'London, United Kingdom')], default='Dhaka, Bangladesh', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_city',
            field=models.CharField(blank=True, choices=[('Dhaka, Bangladesh', 'Dhaka, Bangladesh'), ('Chittagong, Bangladesh', 'Chittagong, Bangladesh'), ('Sylhet, Bangladesh', 'Sylhet, Bangladesh'), ('Gazipur, Bangladesh', 'Gazipur, Bangladesh'), ('Narayangang, Bangladesh', 'Narayangang, Bangladesh'), ('Khulna, Bangladesh', 'Khulna, Bangladesh'), ('London, United Kingdom', 'London, United Kingdom')], default='Dhaka, Bangladesh', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
