# Generated by Django 3.0.3 on 2020-07-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0092_auto_20200718_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
