# Generated by Django 3.0.3 on 2020-07-29 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0093_company_featured'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application_status',
            new_name='ApplicationStatus',
        ),
    ]
