# Generated by Django 3.0.3 on 2020-08-09 05:37

from django.db import migrations, models

def forwards_func(apps, schema_editor):
    City = apps.get_model("job", "City")
    db_alias = schema_editor.connection.alias
    City.objects.using(db_alias).bulk_create([
        City(name="Bangladesh,Barishal"),
        City(name="Bangladesh,Chattagram"),
        City(name="Bangladesh,Dhaka"),
        City(name="Bangladesh,Khulna"),
        City(name="Bangladesh,Mymensingh"),
        City(name="Bangladesh,Rajshahi"),
        City(name="Bangladesh,Rangpur"),
        City(name="Bangladesh,Sylhet"),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('job', '0096_auto_20200808_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_from', models.CharField(max_length=255, null=True)),
                ('modified_by', models.CharField(max_length=255, null=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('modified_from', models.CharField(max_length=255, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_by', models.CharField(max_length=255, null=True)),
                ('archived_at', models.DateTimeField(null=True)),
                ('archived_from', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cities',
            },
        ),
        migrations.RunPython(forwards_func)
    ]
