# Generated by Django 3.0.3 on 2020-08-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0097_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
