# Generated by Django 3.0.3 on 2020-08-09 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0098_auto_20200809_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
    ]
