# Generated by Django 3.0.3 on 2020-08-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0100_job_locked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='approved_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='posted_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='published_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='reviewed_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
