# Generated by Django 3.0.3 on 2020-08-29 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0102_auto_20200826_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='resume',
            new_name='attachment',
        ),
    ]
