# Generated by Django 3.0.3 on 2020-08-29 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0103_auto_20200829_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='cover_letter',
            new_name='resume',
        ),
    ]
