# Generated by Django 3.0.3 on 2020-09-13 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0105_job_salary_option'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gender',
            options={'verbose_name': 'Gender (Pro)', 'verbose_name_plural': 'Genders (Pro)'},
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name': 'Industry', 'verbose_name_plural': 'Industries'},
        ),
        migrations.AlterModelOptions(
            name='jobtype',
            options={'verbose_name': 'Job Type', 'verbose_name_plural': 'Job Types'},
        ),
        migrations.AlterModelOptions(
            name='trendingkeywords',
            options={'verbose_name': 'Trending Keyword', 'verbose_name_plural': 'Trending Keywords'},
        ),
    ]
