# Generated by Django 3.0.3 on 2020-09-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0106_auto_20200913_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
