# Generated by Django 3.0.3 on 2020-02-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0002_auto_20200217_0457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='username',
        ),
        migrations.AddField(
            model_name='professional',
            name='terms_and_condition_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='professional',
            name='email',
            field=models.EmailField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='professional',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='password',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='professional',
            name='phone',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='professional',
            name='professional_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
