# Generated by Django 3.0.3 on 2020-02-22 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import p7.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pro', '0003_auto_20200219_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='user_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='professional',
            name='password',
            field=models.CharField(max_length=255, validators=[p7.validators.check_valid_password, p7.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='professional',
            name='phone',
            field=models.CharField(max_length=255, validators=[p7.validators.check_valid_phone_number]),
        ),
    ]
