# Generated by Django 3.0.3 on 2020-02-22 04:12

from django.db import migrations, models
import p7.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0003_auto_20200219_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='password',
            field=models.CharField(max_length=255, validators=[p7.validators.check_valid_password, p7.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='professional',
            name='phone',
            field=models.CharField(max_length=255, validators=[p7.validators.check_valid_phone_number]),
        ),
    ]
