# Generated by Django 3.0.3 on 2020-02-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0004_auto_20200222_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
