# Generated by Django 3.0.3 on 2020-02-22 05:59

from django.db import migrations, models
import p7.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0004_auto_20200222_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='password',
            field=models.CharField(max_length=255, validators=[p7.validators.check_valid_password]),
        ),
    ]
