# Generated by Django 3.0.3 on 2020-02-22 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0005_auto_20200222_0559'),
        ('pro', '0005_auto_20200222_0648'),
    ]

    operations = [
    ]
