# Generated by Django 3.0.3 on 2020-02-22 11:57

from django.db import migrations, models
import p7.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0006_merge_20200222_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professional',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='professional',
            name='password',
            field=models.CharField(max_length=255, validators=[p7.validators.check_valid_password, p7.validators.MinLengthValidator(8)]),
        ),
    ]
