# Generated by Django 3.0.3 on 2020-02-22 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0006_merge_20200222_1122'),
        ('pro', '0007_auto_20200222_1157'),
    ]

    operations = [
    ]
