# Generated by Django 3.0.3 on 2020-02-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0008_merge_20200222_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='signup_verification_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
