# Generated by Django 3.0.3 on 2020-03-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0009_professional_signup_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='image',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
