# Generated by Django 3.0.3 on 2020-02-29 04:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0009_professional_signup_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
