# Generated by Django 3.0.3 on 2020-03-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0010_auto_20200302_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
