# Generated by Django 3.0.3 on 2020-03-03 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0010_professional_created_date'),
        ('pro', '0011_auto_20200302_1033'),
    ]

    operations = [
    ]
