# Generated by Django 3.0.3 on 2020-03-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0012_merge_20200303_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
