# Generated by Django 3.0.3 on 2020-03-03 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0013_auto_20200303_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
