# Generated by Django 3.0.3 on 2020-03-03 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0015_auto_20200303_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='created_date',
        ),
    ]
