# Generated by Django 3.0.3 on 2020-03-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0017_auto_20200322_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='signup_verification_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
