# Generated by Django 3.0.3 on 2020-03-24 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0018_auto_20200323_1139'),
        ('pro', '0017_auto_20200323_0700'),
    ]

    operations = [
    ]
