# Generated by Django 3.0.3 on 2020-03-28 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0017_auto_20200323_0700'),
        ('pro', '0018_auto_20200323_1139'),
    ]

    operations = [
    ]
