# Generated by Django 3.0.3 on 2020-03-25 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0019_merge_20200324_0643'),
        ('pro', '0019_merge_20200324_0618'),
    ]

    operations = [
    ]
