# Generated by Django 3.0.3 on 2020-03-30 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0020_merge_20200325_0949'),
        ('pro', '0019_merge_20200328_0647'),
    ]

    operations = [
    ]
