# Generated by Django 3.0.3 on 2020-04-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0021_merge_20200330_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='job_alert_status',
            field=models.BooleanField(default=False),
        ),
    ]
