# Generated by Django 3.0.3 on 2020-04-15 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0022_auto_20200413_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='created_date',
        ),
    ]
