# Generated by Django 3.0.3 on 2020-04-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0023_remove_professional_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professionaleducation',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professionalskill',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reference',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='professionalskill',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
