# Generated by Django 3.0.3 on 2020-04-18 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0022_professional_job_alert_status'),
        ('pro', '0026_auto_20200418_0902'),
    ]

    operations = [
    ]
