# Generated by Django 3.0.3 on 2020-04-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0027_merge_20200418_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='currently_working_here',
            field=models.BooleanField(default=False),
        ),
    ]
