# Generated by Django 3.0.3 on 2020-04-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0028_workexperience_currently_working_here'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='current_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
