# Generated by Django 3.0.3 on 2020-04-26 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0031_auto_20200426_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professional',
            old_name='facebbok_id',
            new_name='facebook_id',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='decription',
            new_name='description',
        ),
    ]
