# Generated by Django 3.0.3 on 2020-04-28 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0032_auto_20200426_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='desceription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='Start_date',
            new_name='start_date',
        ),
    ]
