# Generated by Django 3.0.3 on 2020-05-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0033_auto_20200428_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workexperience',
            old_name='currently_working_here',
            new_name='is_currently_working',
        ),
        migrations.AddField(
            model_name='workexperience',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
