# Generated by Django 3.0.3 on 2020-05-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0034_prorecentactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionaleducation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionaleducation',
            name='is_ongoing',
            field=models.BooleanField(default=False),
        ),
    ]
