# Generated by Django 3.0.3 on 2020-05-18 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0034_auto_20200517_1752'),
        ('pro', '0035_auto_20200516_1412'),
    ]

    operations = [
    ]
