# Generated by Django 3.0.3 on 2020-05-18 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0036_merge_20200518_1516'),
        ('pro', '0036_merge_20200518_1011'),
    ]

    operations = [
    ]
