# Generated by Django 3.0.3 on 2020-05-20 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0075_auto_20200518_1428'),
        ('pro', '0036_merge_20200518_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_pic', to='job.Company'),
        ),
    ]
