# Generated by Django 3.0.3 on 2020-05-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0037_auto_20200520_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
