# Generated by Django 3.0.3 on 2020-05-19 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0037_merge_20200519_0551'),
        ('pro', '0036_merge_20200517_2310'),
    ]

    operations = [
    ]
