# Generated by Django 3.0.3 on 2020-05-21 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0038_merge_20200519_1625'),
        ('pro', '0037_auto_20200520_1337'),
    ]

    operations = [
    ]
