# Generated by Django 3.0.3 on 2020-05-21 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0039_merge_20200521_1417'),
        ('pro', '0038_professional_blood_group'),
    ]

    operations = [
    ]
