# Generated by Django 3.0.3 on 2020-06-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0040_merge_20200521_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
