# Generated by Django 3.0.3 on 2020-06-15 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pro', '0041_auto_20200608_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_from', models.CharField(max_length=255, null=True)),
                ('modified_by', models.CharField(max_length=255, null=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('modified_from', models.CharField(max_length=255, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_by', models.CharField(max_length=255, null=True)),
                ('archived_at', models.DateTimeField(null=True)),
                ('archived_from', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recent_activities',
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recent_activities',
            },
        ),
        migrations.RemoveField(
            model_name='certificatename',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='institute',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='major',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='nationality',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='professionaleducation',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='professionaleducation',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='professionalskill',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='professionalskill',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='religion',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='modified_date',
        ),
        migrations.AddField(
            model_name='certificatename',
            name='archived_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='certificatename',
            name='archived_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificatename',
            name='archived_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificatename',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='certificatename',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificatename',
            name='created_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificatename',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certificatename',
            name='modified_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='certificatename',
            name='modified_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificatename',
            name='modified_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='archived_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='archived_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='archived_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='created_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='modified_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='archived_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='archived_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='archived_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='created_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institute',
            name='modified_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='modified_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='modified_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='major',
            name='archived_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='major',
            name='archived_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='major',
            name='archived_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='major',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='major',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='major',
            name='created_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='major',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='major',
            name='modified_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='major',
            name='modified_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='major',
            name='modified_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='archived_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='archived_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='archived_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='created_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='modified_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nationality',
            name='archived_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='nationality',
            name='archived_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nationality',
            name='archived_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nationality',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='nationality',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nationality',
            name='created_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nationality',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nationality',
            name='modified_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='nationality',
            name='modified_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nationality',
            name='modified_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='archived_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='archived_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='archived_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='created_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='modified_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='modified_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='modified_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='archived_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='archived_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='archived_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='created_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='modified_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='archived_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='archived_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='archived_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='created_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professional',
            name='modified_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='professionaleducation',
            name='archived_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='professionaleducation',
            name='archived_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professionaleducation',
            name='archived_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professionaleducation',
            name='created_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professionaleducation',
            name='modified_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professionalskill',
            name='archived_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='professionalskill',
            name='archived_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professionalskill',
            name='archived_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professionalskill',
            name='created_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professionalskill',
            name='modified_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='archived_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='archived_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='archived_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='created_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='modified_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='religion',
            name='archived_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='religion',
            name='archived_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='religion',
            name='archived_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='religion',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='religion',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='religion',
            name='created_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='religion',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='religion',
            name='modified_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='religion',
            name='modified_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='religion',
            name='modified_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='archived_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='archived_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='archived_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='created_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='modified_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='certification',
            name='created_at',
        ),
        migrations.AddField(
            model_name='certification',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='certification',
            name='modified_at',
        ),
        migrations.AddField(
            model_name='certification',
            name='modified_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='modified_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certifications', to='pro.Professional'),
        ),
        migrations.RemoveField(
            model_name='membership',
            name='created_at',
        ),
        migrations.AddField(
            model_name='membership',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='membership',
            name='modified_at',
        ),
        migrations.AddField(
            model_name='membership',
            name='modified_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='modified_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='pro.Professional'),
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='created_at',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='modified_at',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='modified_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='modified_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portfolios', to='pro.Professional'),
        ),
        migrations.RemoveField(
            model_name='professional',
            name='created_at',
        ),
        migrations.AddField(
            model_name='professional',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='professional',
            name='modified_at',
        ),
        migrations.AddField(
            model_name='professional',
            name='modified_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='modified_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='professionaleducation',
            name='created_at',
        ),
        migrations.AddField(
            model_name='professionaleducation',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='professionaleducation',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='professionaleducation',
            name='modified_at',
        ),
        migrations.AddField(
            model_name='professionaleducation',
            name='modified_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='professionaleducation',
            name='modified_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='professionaleducation',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='educations', to='pro.Professional'),
        ),
        migrations.RemoveField(
            model_name='professionalskill',
            name='created_at',
        ),
        migrations.AddField(
            model_name='professionalskill',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='professionalskill',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='professionalskill',
            name='modified_at',
        ),
        migrations.AddField(
            model_name='professionalskill',
            name='modified_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='professionalskill',
            name='modified_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='professionalskill',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='pro.Professional'),
        ),
        migrations.RemoveField(
            model_name='reference',
            name='created_at',
        ),
        migrations.AddField(
            model_name='reference',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='reference',
            name='modified_at',
        ),
        migrations.AddField(
            model_name='reference',
            name='modified_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='modified_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='references', to='pro.Professional'),
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='created_at',
        ),
        migrations.AddField(
            model_name='workexperience',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='modified_at',
        ),
        migrations.AddField(
            model_name='workexperience',
            name='modified_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='modified_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_experiences', to='pro.Professional'),
        ),
        migrations.DeleteModel(
            name='ProRecentActivity',
        ),
    ]
