# Generated by Django 3.0.3 on 2020-06-20 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0085_auto_20200615_1427'),
        ('pro', '0042_auto_20200615_1427'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='professionalskill',
            unique_together={('professional', 'skill_name')},
        ),
        migrations.AlterModelTable(
            name='professionalskill',
            table='professional',
        ),
    ]
