# Generated by Django 3.0.3 on 2020-06-21 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0043_auto_20200620_1658'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='professionalskill',
            table='professional_skills',
        ),
    ]
