# Generated by Django 3.0.3 on 2020-06-21 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0044_auto_20200621_0953'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='professionalskill',
            unique_together=set(),
        ),
    ]
