# Generated by Django 3.0.3 on 2020-06-29 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0045_auto_20200621_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
