# Generated by Django 3.0.3 on 2020-07-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0046_auto_20200629_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='full_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
