# Generated by Django 3.0.3 on 2020-07-28 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0093_company_featured'),
        ('pro', '0049_auto_20200720_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionaleducation',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='job.Qualification'),
        ),
    ]
