# Generated by Django 3.0.3 on 2020-08-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0051_auto_20200808_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='certifyingorganization',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='institute',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='membershiporganization',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
