# Generated by Django 3.0.3 on 2020-09-08 10:13

from django.db import migrations, models
import p7.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0053_auto_20200906_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[p7.validators.check_valid_phone_number]),
        ),
    ]
